config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  post 'welcome/create'
  get 'welcome/new_index'
  get 'welcome/exercise'

  root 'sessions#new'
  get '/increase', to: redirect('https://www.trifectanutrition.com/paleo-meal-delivery'), as: :increase
  get '/decrease', to: redirect('https://www.trifectanutrition.com/vegetarian-meal-delivery'), as: :decrease
  get '/maintain', to: redirect('https://www.trifectanutrition.com/clean-eating-meal-delivery'), as: :maintain

  resources :users
  resources :sessions, only: [:new, :destroy, :create]
  resources :restaurants








end

app/models/user.rb
class User < ActiveRecord::Base
  self.primary_key = "uid"
  validates :username, presence: { message: "username cannot be blank"}
  validates :username, uniqueness: { message: "username already existed"}
  validates :password, presence: { message: "password cannot be blank"}
  validates :password, length: { minimum: 6, message: "password should be more than 6 chars"}
  validates :first_name, presence: { message: "first_name cannot be blank"}
  validates :last_name, presence: { message: "last_name cannot be blank"}
  validates :email, presence: { message: "email cannot be blank"}
  # validates :weight, presence: { message: "weight cannot be blank"}
  # validates :height, presence: { message: "height cannot be blank"}
  # validates :age, presence: { message: "age cannot be blank"}
  # validates :sex, presence: { message: "sex cannot be blank"}

  def calculate(uid)
    @user = User.find_by(uid)
    # Increase the weight is 1, decrease is 2, maintain is 0.
    if @user.user_type.eql?("1")
      @user.daily_calorie = (((@user.goal_weight - @user.weight) * 7700) / @user.days).round()
    elsif @user.user_type.eql?("2")
      @user.daily_calorie = -(((@user.weight - @user.goal_weight) * 7700) / @user.days).round()
    else
      @user.daily_calorie = 0
    end
    @user.save
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :auth_user, only: [:edit, :update, :destroy]
  def new
    @user = User.new
  end

  # register new user
  def create
    @user = User.new(params.require(:user).permit(:username, :password, :first_name, :last_name,
                                                  :email, :weight, :height, :age, :sex))

    if params[:user][:password].length < 6
      flash[:notice] = "Please make sure your password at least 6 characters long!"
      render action: :new
    elsif params[:user][:password] != params[:confirmPW][:confirmPW]
      flash[:notice] = "Please make sure you confirm password match your password!"
      render action: :new
    elsif User.exists? :username => params[:user][:username]
      flash[:notice] = "Username already existed!"
      render action: :new
    elsif @user.save
      flash[:notice] = "Registered successfully!"
      session[:user_uid] = @user.uid
      redirect_to welcome_new_index_path
    else
      flash[:notice] = "Register failed!"
      render action: :new
    end
  end

  def edit
    @user = User.find(session[:user_uid])
  end

  def update
    @user = User.find_by(uid: session[:user_uid])
    @user.first_name = params[:user][:first_name] unless (params[:user][:first_name].nil? or params[:user][:first_name].blank?)
    @user.last_name = params[:user][:last_name] unless (params[:user][:last_name].nil? or params[:user][:last_name].blank?)
    @user.email = params[:user][:email] unless (params[:user][:email].nil? or params[:user][:email].blank?)
    @user.weight = params[:user][:weight] unless (params[:user][:weight].nil? or params[:user][:weight].blank?)
    @user.height = params[:user][:height] unless (params[:user][:height].nil? or params[:user][:height].blank?)
    @user.age = params[:user][:age] unless (params[:user][:age].nil? or params[:user][:age].blank?)
    @user.sex = params[:user][:sex] unless (params[:user][:sex].nil? or params[:user][:sex].blank?)
    @user.goal_weight = params[:user][:goal_weight] unless (params[:user][:goal_weight].nil? or params[:user][:goal_weight].blank?)
    @user.days = params[:user][:days] unless (params[:user][:days].nil? or params[:user][:days].blank?)
    @user.user_type = params[:user][:user_type] unless (params[:user][:user_type].nil? or params[:user][:user_type].blank?)
    if @user.save
      @user.calculate uid: session[:user_uid]
      flash[:notice] = "You have changed your profiles!"
      redirect_to welcome_index_path
      return
    end
  end

  def destroy
    @user = User.find_by(uid: session[:user_uid])
    @user.destroy
    session[:user_uid] = nil
    flash[:notice] = "You have been Deleted your account!"
    redirect_to root_path
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Document</title>
  <style>
      *{
          margin: 0;
          padding: 0;
          list-style: none;
          text-decoration: none;
      }

      @font-face {
          font-family: 'iconfont';  /* Project id 3741053 */
          src: url('//at.alicdn.com/t/c/font_3741053_lf4z8drci5c.woff2?t=1667235492068') format('woff2'),
          url('//at.alicdn.com/t/c/font_3741053_lf4z8drci5c.woff?t=1667235492068') format('woff'),
          url('//at.alicdn.com/t/c/font_3741053_lf4z8drci5c.ttf?t=1667235492068') format('truetype');
      }
      .iconfont{
          font-family:"iconfont" !important;
          font-size:16px;font-style:normal;
          -webkit-font-smoothing: antialiased;
          -webkit-text-stroke-width: 0.2px;
          -moz-osx-font-smoothing: grayscale;}

      body {
          position: relative;
          /* background-color: rgb(249, 250, 255); */
          /* background-color: white; */
          background-image: url(/assets/pic.jpg);
          background-repeat: no-repeat;
          background-size: 650px;
          background-position: bottom 0 right 0 ;
          color: rgb(64, 77, 85);
      }
      .box {
          /* background-color: white; */
          height: calc(100vh - 100px);
          /* width: 700px; */
          padding-left:80px ;
          margin-top: 20px;
      }
      input {
          height: 35px;
          width: 350px;
          border: rgb(215, 216, 217) 1.5px solid;
          margin:8px 0px 30px 0px;
          /* outline-color: rgb(169, 176, 181);  */
          background-color: transparent;
          color: rgb(64, 77, 85); ;
      }
      ::placeholder{
          color: rgb(212, 213, 215);

      }
      .bigtitle {
          font-size: 55px;
          font-weight: 800;
          border-bottom:2px dashed rgb(215, 216, 217);
          margin-top: 25px;
      }

      #button {
          color: white;
          font-size: 18px;
          background-color: rgb(69, 67, 226);
          width: 120px;
          height: 45px;
          border: rgb(69, 67, 226) 1px solid;
          float:right;
          display: inline

      }
      .aimg img{
          position: absolute;
          /* height: 650px; */
          width: 550px;
          bottom:-120px;
          right: 0px;
      }
      .member{
          height: 40px;
          /* background-color: aqua; */
      }
      .member a{
          color:rgb(69, 67, 226) ;
      }
      .member a:hover{
          color: rgb(60, 61, 61);
      }
  </style>
</head>
<body>

<div class="box" style="width:800px ;">

  <div class="bigtitle">
    <span  style="margin-bottom: -4px">Modify <br></span>
    <span >Information</span>
  </div>

<!--  <form action="">-->
  <%=form_for @user, url: user_path, method: :put do |f| %>
    <div style="height: 430px;  border-bottom:2px dashed rgb(215, 216, 217);">
      <div style="float: left; display: inline; margin-top: 20px;">
        <div>
          <span class="input-box">First name <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="change your first name" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :first_name, id:"first_name" %>
        </div>

        <div>
          <span class="input-box">Sex<button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="change your sex here" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :sex, id:"sex"%>
        </div>

        <div>
          <span class="input-box">Age <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="change your age here" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :age, id:"age"%>
        </div>

        <div>
          <span class="input-box">Weight (Kg)<button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="change your current weight here" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :weight, id:"weight"%>
        </div>

        <div>
          <span class="input-box">Days <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="change your expected days here" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :days, id:"days"%>
        </div>
      </div>

      <div style=" float: right; display: inline; margin-top: 20px;">
        <div>
          <span class="input-box">Last name <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="change your last name here" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :last_name, id:"last_name"%>
        </div>

        <div>
          <span class="input-box">Email <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="change your email here" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :email, id:"email" %>
        </div>

        <div>
          <span class="input-box">Height (cm) <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="change your height here" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :height, id:"height" %>
        </div>

        <div>
          <span class="input-box">Goal Weight (Kg) <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="change your goal weight here" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :goal_weight, id:"goal_weight"%>
        </div>

        <div style="margin-top: 6px">
          <div>You want to <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="change your goal type here" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></div>
          <select class="form-select" name="user[user_type]">
            <option selected>Open this select menu</option>
            <option value="1">Increase weight</option>
            <option value="2">Decrease weight</option>
            <option value="3">Maintain weight</option>
          </select>
        </div>
      </div>
    </div>

  <div style="height:20px; margin-top: 100px;" >
    <%= f.submit "Update", id: "button" %>
  </div>
  <% end -%>
</div>
<script>
    [...document.querySelectorAll('[data-bs-toggle="tooltip"]')]
        .forEach(el => new bootstrap.Tooltip(el))
</script>
</body>

app/views/users/new.html.erb
<!--register page-->

<head>
  <meta charset="UTF-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Document</title>
  <style>
      * {
          margin: 0;
          padding: 0;
          list-style: none;
          text-decoration: none;
      }

      @font-face {
          font-family: 'iconfont';  /* Project id 3741053 */
          src: url('//at.alicdn.com/t/c/font_3741053_lf4z8drci5c.woff2?t=1667235492068') format('woff2'),
          url('//at.alicdn.com/t/c/font_3741053_lf4z8drci5c.woff?t=1667235492068') format('woff'),
          url('//at.alicdn.com/t/c/font_3741053_lf4z8drci5c.ttf?t=1667235492068') format('truetype');
      }

      .iconfont {
          font-family: "iconfont" !important;
          font-size: 16px;
          font-style: normal;
          -webkit-font-smoothing: antialiased;
          -webkit-text-stroke-width: 0.2px;
          -moz-osx-font-smoothing: grayscale;
      }

      body {
          position: relative;
          /* background-color: rgb(249, 250, 255); */
          /* background-color: white; */
          background-image: url(/assets/pic.jpg);
          background-repeat: no-repeat;
          background-size: 580px;
          background-position: bottom 0 right 0;
          color: rgb(64, 77, 85);
      }

      .box {
          background-color: white;
          height: calc(100vh - 100px);
          /* width: 700px; */
          padding-left: 80px;
          margin-top: 20px;
      }

      input {
          height: 35px;
          width: 350px;
          border: rgb(215, 216, 217) 1.5px solid;
          margin: 8px 0px 30px 0px;
          outline-color: rgb(169, 176, 181);
          color: rgb(64, 77, 85);;
      }

      ::placeholder {
          color: rgb(212, 213, 215);

      }

      .bigtitle {
          font-size: 55px;
          font-weight: 800;
          border-bottom: 2px dashed rgb(215, 216, 217);
          margin-top: 25px;
      }

      #button {
          color: white;
          font-size: 18px;
          background-color: rgb(69, 67, 226);
          width: 120px;
          height: 45px;
          border: rgb(69, 67, 226) 1px solid;
          float: right;
          display: inline

      }

      .aimg img {
          position: absolute;
          /* height: 650px; */
          width: 550px;
          bottom: 0px;
          right: 10px;
      }

      .navlist li {
          color: rgb(64, 77, 85);
          float: left;
          height: 100%;
          line-height: 35px;
          text-align: center;
          font-size: 18px;

      }

      .navlist a {
          color: black;
          display: block;
      }

      .navlist a:hover {
          color: rgb(76, 74, 237);
          /* background-color:rgb(244, 243, 249) ; */
      }

      .member {
          height: 40px;
          /* background-color: aqua; */
      }

      .member a {
          color: rgb(69, 67, 226);
      }

      .member a:hover {
          color: rgb(60, 61, 61);
      }
  </style>
</head>

<body>
  <div class="box" style="width:800px ;">

    <div class="bigtitle">
      <span style="margin-bottom: -4px">Register <br></span>
      <span>information</span>
    </div>

    <!--  <form action="">-->
    <%= form_for @user, url: users_path, method: :post do |f| %>

      <div style="height: 250px;  border-bottom:2px dashed rgb(215, 216, 217);">
        <div style="float: left; display: inline; margin-top: 20px;">
          <div>
            <span class="input-box">Fist name <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="first name is required" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
            <%= text_field :user, :first_name, id: "first_name" %>
          </div>
          <div>
            <span class="input-box">Username <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="username is required" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
            <%= text_field :user, :username, id: "username" %>
          </div>
        </div>

        <div style=" float: right; display: inline; margin-top: 20px;">
          <div>
            <span class="input-box">Last name <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="last name is required" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
            <%= text_field :user, :last_name, id: "last_name" %>
          </div>

          <div>
            <span class="input-box">Email <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="email is required" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
            <%= text_field :user, :email, id: "email" %>
          </div>
        </div>
      </div>

      <div style="height:120px; padding-top: 30px; border-bottom:2px dashed rgb(215, 216, 217);">
        <div style="float: left;">
          <span class="input-box">Password <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="your password should at least 6 chars long" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :password, id: "password" %>
        </div>
        <div style="float: right; ">
          <span class="input-box">Confirm password<button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="confirm password should be same as the password" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <!--        <input type="text">-->
          <%= text_field :confirmPW, :confirmPW, id: "confirmPW" %>
        </div>
      </div>

      <div style="height:20px; margin-top: 100px;">
        <!--      <button>register</button>-->
        <%#= f.submit "register", class: "btn btn-primary", id: "button" %>
        <%= f.submit "register", id: "button" %>
      </div>

      <!--  </form>-->
    <% end -%>
  </div>
  <script>
      [...document.querySelectorAll('[data-bs-toggle="tooltip"]')]
          .forEach(el => new bootstrap.Tooltip(el))
  </script>
</body>