config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  post 'welcome/create'
  get 'welcome/new_index'
  get 'welcome/exercise'

  root 'sessions#new'
  get '/increase', to: redirect('https://www.trifectanutrition.com/paleo-meal-delivery'), as: :increase
  get '/decrease', to: redirect('https://www.trifectanutrition.com/vegetarian-meal-delivery'), as: :decrease
  get '/maintain', to: redirect('https://www.trifectanutrition.com/clean-eating-meal-delivery'), as: :maintain

  resources :users
  resources :sessions, only: [:new, :destroy, :create]
  resources :restaurants








end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @user = User.find(session[:user_uid])
  end

  def new_index
    @user = User.find(session[:user_uid])
  end

  def create
    @user = current_user
    if params[:user][:user_type] == "Open this select menu"
      flash[:notice] = "Please choose an option in the bottom drop down window!"
      render action: :new_index
      return
    elsif params[:user][:weight].to_f != 0.0 and params[:user][:height].to_f != 0.0 and params[:user][:age].to_i != 0 and params[:user][:goal_weight].to_f != 0.0 and params[:user][:days].to_i != 0
      @user.height = params[:user][:height]
      @user.age = params[:user][:age]
      @user.weight = params[:user][:weight]
      @user.goal_weight = params[:user][:goal_weight]
      @user.days = params[:user][:days]
    else
      flash[:notice] = "Please make sure your weight, height, age and days are digit!"
      render action: :new_index
      return
    end

    @user.sex = params[:user][:sex]
    @user.user_type = params[:user][:user_type]

    if @user.save
      flash[:notice] = "Now let's start your goal!"
      @user.calculate(uid: session[:user_uid])
      render action: :index
      return
    end

    flash[:notice] = "Please check your input valid!"
    render action: :new_index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/exercise.html.erb
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Title</title>

</head>
<body>
  <div class="container">
    <div class="row text-center">
      <h1>Calories Burned in 30-minute activities</h1>
    </div>
    <div class="row">
      <table class="table table-hover col-md-12">
        <thead>
        <tr>
          <th scope="col">Gym Activities</th>
          <th scope="col">125-pound person</th>
          <th scope="col">155-pound person</th>
          <th scope="col">185-pound person</th>
        </tr>
        </thead>
        <tbody>
          <tr>
            <td>Weight Lifting: general</td>
            <td>90</td>
            <td>108</td>
            <td>126</td>
          </tr>
          <tr>
            <td>Aerobics: water</td>
            <td>120</td>
            <td>144</td>
            <td>168</td>
          </tr>
          <tr>
            <td>Stretching, Hatha Yoga</td>
            <td>120</td>
            <td>144</td>
            <td>168</td>
          </tr>
          <tr>
            <td>Calisthenics: moderate</td>
            <td>135</td>
            <td>162</td>
            <td>189</td>
          </tr>
          <tr>
            <td>Stair Step Machine: general</td>
            <td>180</td>
            <td>216</td>
            <td>252</td>
          </tr>
          <tr>
            <td>Weight Lifting: vigorous</td>
            <td>180</td>
            <td>216</td>
            <td>252</td>
          </tr>
          <tr>
            <td>Aerobics, Step: low impactr</td>
            <td>210</td>
            <td>252</td>
            <td>294</td>
          </tr>
          <tr>
            <td>Aerobics: high impact</td>
            <td>210</td>
            <td>252</td>
            <td>294</td>
          </tr>
          <tr>
            <td>Bicycling, Stationary: moderate</td>
            <td>210</td>
            <td>252</td>
            <td>294</td>
          </tr>
          <tr>
            <td>Rowing, Stationary: moderate</td>
            <td>210</td>
            <td>252</td>
            <td>294</td>
          </tr>
          <tr>
            <td>Calisthenics: vigorous</td>
            <td>240</td>
            <td>306</td>
            <td>336</td>
          </tr>
          <tr>
            <td>Circuit Training: general</td>
            <td>240</td>
            <td>----</td>
            <td>----</td>
          </tr>
          <tr>
            <td>Rowing, Stationary: vigorous</td>
            <td>255</td>
            <td>369</td>
            <td>440</td>
          </tr>
          <tr>
            <td>Elliptical Trainer: general</td>
            <td>270</td>
            <td>324</td>
            <td>378</td>
          </tr>
          <tr>
            <td>Ski Machine: general</td>
            <td>285</td>
            <td>342</td>
            <td>399</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</body>

app/views/welcome/index.html.erb
<!--user main page-->
<!--<p>Welcome! <%#= User.find(session[:user_uid]).first_name %></p>-->
<%#= link_to "#{@user.first_name}, Logout", session_path(@user), method: 'delete', :class => 'nav-link' %>
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
      * {
          margin: 0;
          padding: 0;
          list-style: none;
          text-decoration: none;
      }

      @font-face {
          font-family: 'iconfont';  /* Project id 3741053 */
          src: url('//at.alicdn.com/t/c/font_3741053_lf4z8drci5c.woff2?t=1667235492068') format('woff2'),
          url('//at.alicdn.com/t/c/font_3741053_lf4z8drci5c.woff?t=1667235492068') format('woff'),
          url('//at.alicdn.com/t/c/font_3741053_lf4z8drci5c.ttf?t=1667235492068') format('truetype');
      }

      .iconfont {
          font-family: "iconfont" !important;
          font-size: 16px;
          font-style: normal;
          -webkit-font-smoothing: antialiased;
          -webkit-text-stroke-width: 0.2px;
          -moz-osx-font-smoothing: grayscale;
      }

      .dashboard {
          background-color: white;
          float: left;
          width: 20%;
          height: 100%;
          border-radius: 0 18px 18px 0px;
          /* position: relative; */

      }

      .content {
          /*background-color:rgb(244, 243, 249);*/
          /*background-color: rgb(244, 243, 249);*/
          float: left;
          width: 80%;
          height: 100%;
          /*position: absolute;*/
          /*right: -20px;*/
          /*top: 30px;*/

      }

      body {
          background-color: rgb(244, 243, 249);
      }

      .information-aa {
          background-color: white;
          width: 45%;
          margin-left: 5%;
      }

      .weight {
          background-color: white;
          width: 50%;
          /*margin-top: 70px;*/
          padding-left: 80px;
          position: relative;
      }

      .pic {
          background-image: url(/assets/tu.png);
          background-size: 80%;
          background-repeat: no-repeat;
          height: 240px;
          width: 300px;
          margin-left: 189px;
          margin-top: 70px;
      }

      .ww {
          background-color: white;
          height: 255px;
          margin-left: 37px;
          border-radius: 10px;
      }

      .a-dashboard {
          color: rgb(76, 74, 237);
          font-size: 18px;
          font-weight: 600;
          background-color: rgb(227, 225, 255);
          width: 250px;
          height: 45px;
          border: rgb(227, 225, 255) 1px solid;
          border-radius: 8px;
      }

      .b-dashboard {
          color: rgb(133, 135, 136);
          font-size: 18px;
          font-weight: 600;
          background-color: white;
          width: 250px;
          height: 45px;
          border: rgb(248, 247, 249) 1px solid;
          border-radius: 8px;
          margin-top: 130%;
      }

      .information-aa button {
          color: rgb(76, 74, 237);
          font-size: 18px;
          font-weight: 600;
          background-color: white;
          width: 350px;
          height: 45px;
          border: rgb(149, 143, 225) 1px solid;
          border-radius: 20px;
      }

      .ww p {
          margin: 15px 15px;
          color: rgb(159, 162, 164);

      }

      .ww h1 {
          text-align: center;
          margin-top: 80px;
      }

      .weight span {
          position: absolute;
          margin-top: 50px;
      }
  </style>
</head>
<body>
<div class="container" name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <div class="dashboard">
    <p style="margin:85px 12px; font-size: 30px">Calorie<span style="color:rgb(61, 50, 214); ">Manager</span></p>
    <button class="a-dashboard" style="margin:10px 3px;"><i class="iconfont">&#xe653;</i>Dashboard</button>
    <button class="b-dashboard">
      <span style="margin-right:15px;"> ← </span><%= link_to "Log Out", session_path(session[:user_uid]), method: 'delete', class: 'text-secondary' %>
    </button>
  </div>

  <div class="content">
    <div class="container">
      <div class="row">
        <div class="information-aa">
          <div class="row">
            <p style="font-size:50px; font-weight:800;margin-top: 65px;  ">Hi,<%= current_user.first_name %></p>
          </div>
          <div class="row">
            <div class="col-md-6">
              <p style="font-size:20px; font-weight:800; margin-top:40px ; color: rgb(100, 204, 155); ">-2.25kg</p>
              <p style="font-size:15px; font-weight:500; margin-bottom: 40px; color: rgb(136, 140, 139); ">This Week</p>
            </div>
            <div class="col-md-6" style="margin-top: 35px">
               Today, you need <br>
              <span class="text-danger"><%= current_user.daily_calorie %> Calories</span> <br>
               calorie deficit(-)/calorie surplus(+)
            </div>
          </div>
          <div class="row">
            <button style="margin-bottom: 35px">KEEP GOING!</button>
          </div>
        </div>

        <div class="weight">
          <span style="margin: 140px 0 0 290px; font-size:40px;color:white"><%= current_user.weight %> KG</span>
          <div class="pic"></div>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <div class="age ww">
            <p>Age</p>
            <h1><%= current_user.age %></h1>
          </div>
        </div>
        <div class="col">
          <div class="age ww">
            <p>Sex</p>
            <h1><%= current_user.sex %></h1>
          </div>
        </div>
        <div class="col">
          <div class="age ww">
            <p>Height</p>
            <h1><%= current_user.height %>CM</h1>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</body>

app/views/welcome/new_index.html.erb
<!--register success-->
<head>
  <meta charset="UTF-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Document</title>
  <style>
      * {
          margin: 0;
          padding: 0;
          list-style: none;
          text-decoration: none;
      }

      @font-face {
          font-family: 'iconfont';  /* Project id 3741053 */
          src: url('//at.alicdn.com/t/c/font_3741053_lf4z8drci5c.woff2?t=1667235492068') format('woff2'),
          url('//at.alicdn.com/t/c/font_3741053_lf4z8drci5c.woff?t=1667235492068') format('woff'),
          url('//at.alicdn.com/t/c/font_3741053_lf4z8drci5c.ttf?t=1667235492068') format('truetype');
      }

      .iconfont {
          font-family: "iconfont" !important;
          font-size: 16px;
          font-style: normal;
          -webkit-font-smoothing: antialiased;
          -webkit-text-stroke-width: 0.2px;
          -moz-osx-font-smoothing: grayscale;
      }

      body {
          position: relative;
          /* background-color: rgb(249, 250, 255); */
          background-color: white;
          color: rgb(64, 77, 85);
      }

      .box {
          background-color: white;
          height: calc(100vh - 100px);
          /* width: 700px; */
          padding-left: 80px;
          margin-top: 20px;
      }

      input {
          height: 35px;
          width: 350px;
          border: rgb(215, 216, 217) 1.5px solid;
          margin: 8px 0px 30px 0px;
          outline-color: rgb(169, 176, 181);
          color: rgb(64, 77, 85);;
      }

      ::placeholder {
          color: rgb(212, 213, 215);

      }

      .bigtitle {
          font-size: 65px;
          font-weight: 700;
          border-bottom: 2px dashed rgb(215, 216, 217);
      }

      .button1 {
          color: white;
          font-size: 18px;
          background-color: rgb(69, 67, 226);
          width: 120px;
          height: 45px;
          border: rgb(69, 67, 226) 1px solid;
          float: right;
          display: inline

      }

      .aimg img {
          position: absolute;
          /* height: 650px; */
          width: 550px;
          bottom: 10px;
          right: 0px;
      }

      .navlist li {
          color: rgb(64, 77, 85);
          float: left;
          height: 100%;
          line-height: 35px;
          text-align: center;
          font-size: 18px;

      }

      .navlist a {
          color: black;
          display: block;
      }

      .navlist a:hover {
          color: rgb(76, 74, 237);
          /* background-color:rgb(244, 243, 249) ; */
      }
  </style>
</head>
<body>
<!-- <script src="../bootstrap/jquery-3.5.1.min.js"></script>
<script src="../bootstrap/js/bootstrap.min.js"></script> -->
<div class="box" style="width:800px ;">
  <br>
  <div class="bigtitle">
    <span>Register Success!</span><br>
    <span style="font-size: 23px;margin-top:5px;">Let us learn more about you</span>
  </div>

  <div style="height: 430px;  border-bottom:2px dashed rgb(215, 216, 217);">
    <%= form_for @user, url: welcome_create_path, method: :post do |f| %>
      <div style="float: left; display: inline; margin-top: 20px;">
        <div>
          <span class="input-box">Height <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="Enter your height" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :height %>
        </div>
        <div>
          <span class="input-box">Sex <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="Enter your sex" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :sex %>
        </div>
        <div>
          <span class="input-box">Goal Weight (Kg) <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="You desired weight is?" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :goal_weight %>
        </div>
      </div>
      <div style=" float: right; display: inline; margin-top: 20px;">
        <div>
          <span class="input-box">Weight (Kg) <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="Enter your weight" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :weight %>
        </div>
        <div>
          <span class="input-box">Age <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="Enter your age" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :age %>
        </div>
        <div>
          <span class="input-box">Days <button type="button" class="btn" data-bs-toggle="tooltip" data-bs-placement="top" title="You want the following days to achieve your goal" style="float:right;"><img src="/assets/wenhao.png" alt="" height="18px" style="float:right;"></button></span><br>
          <%= text_field :user, :days %>
        </div>
      </div>
      <div class="row justify-content-center">
        You want to
      </div>
      <div class="row justify-content-center">
        <div class="col-4">
          <select class="form-select" name="user[user_type]">
            <option selected>Open this select menu</option>
            <option value="1">Increase weight</option>
            <option value="2">Decrease weight</option>
            <option value="3">Maintain weight</option>
          </select>
        </div>
      </div>
      </div>
      <div style="height:20px">
        <%= f.submit "Add", class: "button1" %>
      </div>
    <% end -%>
    </div>
<div class="aimg">
  <img src="/assets/pic.jpg" alt="">
</div>
<script>
    [...document.querySelectorAll('[data-bs-toggle="tooltip"]')]
        .forEach(el => new bootstrap.Tooltip(el))
</script>
</body>


app/views/welcome/restaurant.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="../css/bootstrap.css" rel="stylesheet">
</head>
<body>
  <div class="container">
    <div class="row text-center">
      <h1>Please go to the following restaurants</h1>
    </div>
    <div class="row">
      <table class="table table-hover col-md-12">
        <thead>
        <tr>
          <th scope="col">Restaurant Name</th>
          <th scope="col">Location</th>
          <th scope="col">Label</th>
        </tr>
        </thead>
        <tbody>

    <% Restaurant.all.each do |restaurant| %>
          <% if User.find(session[:user_uid]).user_type == "1" %>
            <% if restaurant.cal_type == "high" || restaurant.cal_type == "medium" %>
              <tr>
                <td>
                  <%= restaurant.name %>
                </td>
                <td>
                  <%= restaurant.location %>
                </td>
                <td>
                  <%= restaurant.cal_type %>
                </td>
              </tr>
            <% end %>
          <% end %>
          <% if User.find(session[:user_uid]).user_type == "2" %>
            <% if restaurant.cal_type == "low" || restaurant.cal_type == "medium" %>
              <tr>
                <td>
                  <%= restaurant.name %>
                </td>
                <td>
                  <%= restaurant.location %>
                </td>
                <td>
                  <%= restaurant.cal_type %>
                </td>
              </tr>
            <% end %>
          <% end %>
          <% if User.find(session[:user_uid]).user_type == "3" %>
            <% if restaurant.cal_type == "low" || restaurant.cal_type == "medium" || restaurant.cal_type == "high" %>
              <tr>
                <td>
                  <%= restaurant.name %>
                </td>
                <td>
                  <%= restaurant.location %>
                </td>
                <td>
                  <%= restaurant.cal_type %>
                </td>
              </tr>
            <% end %>
          <% end %>
    <% end %>
        </tbody>
      </table>
    </div>
  </div>
</body>
</html>