config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  post 'welcome/create'
  get 'welcome/new_index'
  get 'welcome/exercise'

  root 'sessions#new'
  get '/increase', to: redirect('https://www.trifectanutrition.com/paleo-meal-delivery'), as: :increase
  get '/decrease', to: redirect('https://www.trifectanutrition.com/vegetarian-meal-delivery'), as: :decrease
  get '/maintain', to: redirect('https://www.trifectanutrition.com/clean-eating-meal-delivery'), as: :maintain

  resources :users
  resources :sessions, only: [:new, :destroy, :create]
  resources :restaurants








end

app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info text-center" role="alert" id="notice" >
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CS4152Calories</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
<!--  <nav class="navbar navbar-light" style="background-color: #e3f2fd;">-->
    <div class="container-fluid">
      <span class="navbar-brand">Calories<span style="color:rgb(61, 50, 214); ">Manager</span></span>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <% if logged_in? %>
            <%= link_to "Home", welcome_index_path, method: 'get', :class => 'nav-link' %>
            <%= link_to "Edit", edit_user_path(session[:user_uid]), method: 'get', :class => 'nav-link' %>
            <%= link_to "Delete", user_path(session[:user_uid]), method: 'delete', :class => 'nav-link text-danger', data: { confirm: 'Are you sure you want to delete your account?'} %>
            <%= link_to "Restaurant", restaurants_path, :class => 'nav-link' %>
            <%= link_to "Exercise", welcome_exercise_path, method: 'get', :class => 'nav-link' %>
            <% if current_user.user_type == '1' %>
              <%= link_to "Meal Plan", increase_path, :target => "_blank", :class => 'nav-link' %>
            <% elsif current_user.user_type == '2' %>
              <%= link_to "Meal Plan", decrease_path, :target => "_blank", :class => 'nav-link' %>
            <% else %>
              <%= link_to "Meal Plan", maintain_path, :target => "_blank", :class => 'nav-link' %>
            <% end -%>
            <span class="nav-link active float-end" style="margin-left: 580px">
              <t class="">Welcome!</t>
                <%= link_to "#{current_user.first_name}, Logout", session_path(session[:user_uid]), method: 'delete', :class => 'text-secondary' %>
            </span>
          <% else %>
            <%= link_to 'Home', new_session_path, :class => 'nav-link active'%>
            <%= link_to 'Login', new_session_path, :class => 'nav-link' %>
            <%= link_to 'Register', new_user_path, :class => 'nav-link' %>
          <% end -%>
        </div>
      </div>
    </div>
  </nav>
  <div class="container">
    <%= render 'layouts/flash' %>
    <main id="main">
      <%= yield %>
    </main>
  </div>
  <script type="text/javascript" charset="utf-8">
      function openPopup(link)
      {
          link.hide();
          window.open(link.href,'exam_dialog','toolbar=no,location=no,menubar=no,scrollbars=yes,resizable=no');
          return false;
      }
  </script>
</body>
</html>